spring:
  mvc:
    log-request-details: true
  h2:
    console:
      enabled: true

auth:
  jwt:
    secret: "local"
  google:
    client-id: "clientId"

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE

springdoc:
  default-consumes-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
