spring:
  mvc:
    log-request-details: true
  h2:
    console:
      enabled: true

auth:
  jwt:
    secret: "local"

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
